import { Component } from '@angular/core';

@Component({
  selector: 'app-heroes-list',
  templateUrl: './list.component.html',
  styleUrl: './list.component.css',
})
export class ListComponent {
  public heroeNames: string[] = [
    'Spiderman',
    'Ironman',
    'Hulk',
    'Thor',
    'Capitan America',
    'Viuda Negra',
    'Ojo de Halcon',
    'Antman',
    'Bruja Escarlata',
    'Pantera Negra',
    'Doctor Strange',
    'Capitana Marvel',
    'Falcon',
    'Soldado del Invierno',
    'Vision',
    'War Machine',
    'Spiderman',
    'Ironman',
    'Hulk',
    'Thor',
    'Capitan America',
    'Viuda Negra',
    'Ojo de Halcon',
    'Antman',
    'Bruja Escarlata',
    'Pantera Negra',
    'Doctor Strange',
    'Capitana Marvel',
    'Falcon',
    'Soldado del Invierno',
    'Vision',
    'War Machine',
    'Spiderman',
    'Ironman',
    'Hulk',
    'Thor',
    'Capitan America',
    'Viuda Negra',
    'Ojo de Halcon',
    'Antman',
    'Bruja Escarlata',
    'Pantera Negra',
    'Doctor Strange',
    'Capitana Marvel',
    'Falcon',
    'Soldado del Invierno',
    'Vision',
    'War Machine',
    'Spiderman',
    'Ironman',
    'Hulk',
    'Thor',
    'Capitan America',
    'Viuda Negra',
    'Ojo de Halcon',
    'Antman',
    'Bruja Escarlata',
    'Pantera Negra',
    'Doctor Strange',
    'Capitana Marvel',
    'Falcon',
    'Soldado del Invierno',
    'Vision',
    'War Machine',
    'Spiderman',
    'Ironman',
    'Hulk',
    'Thor',
    'Capitan America',
    'Viuda Negra',
    'Ojo de Halcon',
    'Antman',
    'Bruja Escarlata',
    'Pantera Negra',
    'Doctor Strange',
    'Capitana Marvel',
    'Falcon',
    'Soldado del Invierno',
    'Vision',
    'War Machine',
  ];
  public heroeRemoved?: string = '';

  removeLastHeroe(): void {
    this.heroeRemoved = this.heroeNames.pop();
  }
}
